openapi: 3.0.0
info:
  title: Meow Status API
  description: API that returns cat images based on HTTP status codes.
  version: 1.0.0
  contact:
    name: DevEx Team
    url: https://backstage.yourcompany.com/catalog/meow-status
    email: devex-team@yourcompany.com
servers:
  - url: https://meowstatus.yourcompany.com
    description: Production Server
  - url: http://localhost:3000
    description: Local Development Server
paths:
  /status/{code}:
    get:
      summary: Get a cat image for a status code
      description: Returns a cat image representing the requested HTTP status code.
      parameters:
        - name: code
          in: path
          required: true
          schema:
            type: integer
            example: 404
      responses:
        "200":
          description: A cat image representing the status code.
          content:
            image/jpeg:
              schema:
                type: string
                format: binary
        "400":
          description: Invalid status code.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Invalid status code provided."
        "500":
          description: Server error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Internal server error."
