name: meow_status
description: A Flutter app for displaying cat images along with cute quotes.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # State management with Riverpod
  flutter_riverpod: ^2.0.0

  # HTTP client for making API requests
  dio: ^5.0.0

  # Local storage for storing cute cat quotes
  hive: ^2.0.0
  hive_flutter: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Recommended lints
  flutter_lints: ^5.0.0

  # Integration testing
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true