apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: tech-foundations-hub
  description: Tech Foundations Hub - A centralized documentation and tooling platform for foundational engineering practices.
  annotations:
    github.com/project-slug: your-org/tech-foundations-hub
    backstage.io/techdocs-ref: dir:.
spec:
  type: website
  lifecycle: production
  owner: tech-foundations-team
  system: engineering-platform
  dependsOn:
    - component:default/qa-hub
    - component:default/security-hub
    - component:default/devex-hub
    - resource:default/infra-db
    - resource:default/logging-service
  dependencyOf:
    - component:default/developer-portal
    - component:default/ci-cd-pipeline
    - component:default/platform-engineering-hub
  providesApis:
    - api:default/tech-documentation-api
