// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvhP-a_mrr_Tuo-9nVjcAuyg1za_9AGfg',
    appId: '1:226118697411:web:47f17be350e816816e3d76',
    messagingSenderId: '226118697411',
    projectId: 'meow-status-gemini',
    authDomain: 'meow-status-gemini.firebaseapp.com',
    storageBucket: 'meow-status-gemini.firebasestorage.app',
    measurementId: 'G-RYX1X31JQK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-tyZV1Dv-O288PWRWBWi5QHxaU0o26vI',
    appId: '1:226118697411:android:ba6c4e8d6a8857586e3d76',
    messagingSenderId: '226118697411',
    projectId: 'meow-status-gemini',
    storageBucket: 'meow-status-gemini.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuIbB6mQ_4MLu3Umrt6eY7oUdQM80Lx7c',
    appId: '1:226118697411:ios:dc860388c0d227e56e3d76',
    messagingSenderId: '226118697411',
    projectId: 'meow-status-gemini',
    storageBucket: 'meow-status-gemini.firebasestorage.app',
    iosBundleId: 'com.example.meowStatus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuIbB6mQ_4MLu3Umrt6eY7oUdQM80Lx7c',
    appId: '1:226118697411:ios:dc860388c0d227e56e3d76',
    messagingSenderId: '226118697411',
    projectId: 'meow-status-gemini',
    storageBucket: 'meow-status-gemini.firebasestorage.app',
    iosBundleId: 'com.example.meowStatus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvhP-a_mrr_Tuo-9nVjcAuyg1za_9AGfg',
    appId: '1:226118697411:web:d05ea8de22f1f3976e3d76',
    messagingSenderId: '226118697411',
    projectId: 'meow-status-gemini',
    authDomain: 'meow-status-gemini.firebaseapp.com',
    storageBucket: 'meow-status-gemini.firebasestorage.app',
    measurementId: 'G-N7D48MTMDT',
  );
}
