apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service-with-docs
  description: An example of service with docs
  backstage.io/techdocs-ref:dir:.
spec:
  type: website
  lifecycle: production
  owner: artist-relations-team
  system: artist-engagement-portal
  dependsOn:
    - resource:default/artists-db
  dependencyOf:
    - component:default/artist-web-lookup
  providesApis:
    - artist-api
